version: "3"
services:
  sonos-http:
    build: './node-sonos-http-api'
    ports:
      - "5005:5005"
    expose: 
      - "5005"
    command: npm start
  web-client:
    build: './teamtunes'
    ports: 
      - '3000:3000'
      - '3001:3001' #this is for attaching debugger
    command: npm run debug
    env_file:
      - development.env
    volumes:
      - ./teamtunes/lib:/usr/app/lib
      - ./teamtunes/public:/usr/app/public